config/routes.rb
Rails.application.routes.draw do

  resources :results
  
  root 'pages#results'
  get 'bracket', to: 'pages#bracket'
  get 'grid', to: 'pages#grid'
  get 'faq', to: 'pages#faq'
  get 'refresh_bracket', to: 'pages#refresh_bracket'
  get 'refresh_results', to: 'pages#refresh_results'
  get 'new_bracket', to: 'pages#new_bracket'
  

end

app/views/pages/_empty_game.html.erb
<% if bracket_position_id != '701' %>
<div class="live-top"></div>
<% end %>
<div class="game-cell">
  <div class="team-info info_top">
    <div class="team-seed"></div>
    <div class="team-name"></div>
    <div class="team-score"></div>
  </div>
  <div class="team-info info-bottom">
    <div class="team-seed"></div>
    <div class="team-name"></div>
    <div class="team-score"></div>
  </div>
</div>
<div class="live-bottom"></div>

app/views/pages/_game.html.erb
<% g = @games.find { |g| g.bracket_position_id == bracket_position_id } %>
<% if g.nil? %>
  <%= render partial: 'empty_game', locals: { bracket_position_id: bracket_position_id } %>
<% else %>
  <% if bracket_position_id != "701" %>
    <% if g.game_is_live? %>
      <%= content_tag :div, class: 'live-top', title: g.game_status do %>
        <%= g.game_status %>
      <% end %>
    <% else %>
      <div class='live-top'></div>
    <% end %>
  <% end %>
  <% if g.game_is_live? %>
  <div class='game-cell game-is-live'>
  <% else %>
  <div class='game-cell'>
  <% end %>
    <% if g.team_on_top_is_winner? %>
      <div class='team-info info-top winner'>
    <% else %>
      <div class='team-info info-top'>
    <% end %>
        <div class='team-seed'><%= g.team_on_top_seed %></div>
        <%= content_tag :div, class: 'team-name', title: g.team_on_top_name_full do %>
          <%= g.team_on_top_name_short %>
        <% end %>
        <div class='team-score'><%= g.team_on_top_score %></div>
    </div>
    <% if g.team_on_bottom_is_winner %>
      <div class='team-info info-bottom winner'>
    <% else %>
      <div class='team-info info-bottom'>
    <% end %>
        <div class='team-seed'><%= g.team_on_bottom_seed %></div>
        <%= content_tag :div, class: 'team-name', title: g.team_on_bottom_name_full do %>
          <%= g.team_on_bottom_name_short %>
        <% end %>
        <div class='team-score'><%= g.team_on_bottom_score %></div>
    </div>
  </div>
  <%= content_tag :div, class: 'live-bottom', title: g.square_winner do %>
    <%= g.square_winner %>
  <% end %>
<% end %>

app/views/pages/_participantWithNoResults.html.erb
<tr>
  <% totalPaid = @participant_squares.where(participant_id: participant.id).count * 5 %>
  <td style="text-align:left;"><%= participant.preferred_name %></td>
  <td />
  <td>$<%= totalPaid %></td>
  <td>$0</td>
  <td style='font-weight:bold;color:red;'>$-<%= totalPaid %></td>
</tr>

app/views/pages/_participantWithResults.html.erb
<% resultCounter = 0 %>
<% totalPaid = @participant_squares.where(participant_id: participant.id).count * 5 %>
<% totalWon = 0 %>
<tr>
  <% participant_results = @results.where(participant_id: participant.id) %>  
  <%= content_tag :td, rowspan: participant_results.count + 1, style: "text-align:left;" do %>
    <%= participant.preferred_name %>
  <% end %>

  <% participant_results.each do |result| %>
    <% resultCounter += 1 %>
      <td><%= result.round %></td>
      <td />
      <td>$<%= @payout = @payouts.find_by(round: result.round).game_payout %></td>
      <td />

      <% if !@payout.blank? %>
        <% totalWon += @payout %>
      <% end %>
    </tr>
  <% end %>

  <tr>
    <% profit = totalWon - totalPaid %>
    <td style='font-weight:bold;'>Totals</td>
    <td style='font-weight:bold;'>$<%= totalPaid %></td>
    <td style='font-weight:bold;'>$<%= totalWon %></td>
    <% if profit < 0 %>
    <td style='font-weight:bold;color:red;'>
    <% elsif profit > 0 %>
    <td style='font-weight:bold;color:green;'>
    <% else %>
    <td style='font-weight:bold;'>
    <% end %>
      $<%= profit %>
    </td>
  </tr>
</tr>

app/views/pages/_quadrant.html.erb
<% region = @regions.find_by(quadrant_id: quadrant) %>
<%= content_tag :div, class: "region-info", style: region.style do %>
  <%= region.name %>
<% end %>

<% (1..8).each do |i| %>
  <% offset = (quadrant - 1) * 8 %>
  <% game_id = 200 + offset + i %>
  <%= content_tag :div, id: "game#{game_id}", class: "game-set pre game-xs col-1 pos-#{i}" do %>
    <%= render partial: 'game', locals: { bracket_position_id: game_id.to_s } %>
  <% end %>
<% end %>

<% (1..4).each do |i| %>
  <% offset = (quadrant - 1) * 4 %>
  <% game_id = 300 + offset + i %>
  <%= content_tag :div, id: "game#{game_id}", class: "game-set pre game-xs col-2 pos-#{i}" do %>
    <%= render partial: 'game', locals: { bracket_position_id: game_id.to_s } %>
  <% end %>
<% end %>

<% (1..2).each do |i| %>
  <% offset = (quadrant - 1) * 2 %>
  <% game_id = 400 + offset + i %>
  <%= content_tag :div, id: "game#{game_id}", class: "game-set pre game-xs col-3 pos-#{i}" do %>
    <%= render partial: 'game', locals: { bracket_position_id: game_id.to_s } %>
  <% end %>
<% end %>

<% (1..1).each do |i| %>
  <% game_id = 500 + quadrant %>
  <%= content_tag :div, id: "game#{game_id}", class: "game-set pre game-xs col-4 pos-1" do %>
    <%= render partial: 'game', locals: { bracket_position_id: game_id.to_s } %>
  <% end %>
<% end %>

app/views/pages/_region.html.erb
<% @r = @regions.find_by(quadrant_id: quadrant_id) %>
<% if @r.blank? %>
  <span class='regionHeading'>Enter Region</span>
<% else %>
  <%= content_tag :span, class: 'regionHeading', style: @r.style do %>
    <%= @r.name %>
  <% end %>
<% end %>

app/views/pages/bracket.html.erb
<% provide(:title, "Bracket") %>
<%= stylesheet_link_tag 'bracket', cache: true %>
<div class="bracket-parent" align="center">
  <div class="panel panel-default">
    <div class="panel-heading" align="center" style="font-size:2em;"><%= $year %> Bracket</div>
    <div class="panel-body">
      <div style="padding-left:1em; padding-right:1em;">
        <div id="bracket-top" class="bracket-section">
          <div id="bracket-top-left" class="bracket-region ltr col-sm-6">
            <%= render partial: 'quadrant', locals: { quadrant: 1 } %>
          </div>

          <div id="bracket-top-right" class="bracket-region rtl col-sm-6">
            <%= render partial: 'quadrant', locals: { quadrant: 3 } %>
          </div>
        </div>
        <div id="bracket-middle" class="bracket-section">
          <div id="bracket-final" class="bracket-region ctr">
              <div id="game601" class="game-set pre game-sm col-1 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "601" } %>
              </div>

              <div id="game701" class="game-set pre game-lg championship col-2 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "701" } %>
              </div>

              <div id="game602" class="game-set pre game-sm col-3 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "602" } %>
              </div>
          </div>
        </div>
        <div id="bracket-bottom" class="bracket-section">
          <div id="bracket-bottom-left" class="bracket-region ltr">
            <%= render partial: 'quadrant', locals: { quadrant: 2 } %>
          </div>

          <div id="bracket-bottom-right" class="bracket-region rtl">
            <%= render partial: 'quadrant', locals: { quadrant: 4 } %>
          </div>
        </div>
        <% if $year >= "2015" %>
          <div id="bracket-footer" class="bracket-section">
            <div id="bracket-first" class="bracket-region ctr">
              <div class="region-info">
                <h2 class="region-title" style="font-size:20px;">First Four</h2>
              </div>
              
              <div id="game101" class="game-set pre game-xs sect-1 col-1 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "101" } %>
              </div>
              
              <div id="game102" class="game-set pre game-xs sect-1 col-2 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "102" } %>
              </div>
              
              <div id="game103" class="game-set pre game-xs sect-1 col-3 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "103" } %>
              </div>
              
              <div id="game104" class="game-set pre game-xs sect-1 col-4 pos-1">
                <%= render partial: 'game', locals: { bracket_position_id: "104" } %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<div class="col-sm-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title" align="center" style="font-size:2em;">FAQ</h3>
		</div>
		<div class="panel-body">
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingOne">
						<h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
							What is a 100 square grid pool?
						</a>
						</h4>
					</div>
					<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
						<div class="panel-body">
							A 10x10 grid comprised of 10 rows and 10 columns.  Once each square is filled, the numbers 0 thru 9 will be randomly drawn across the top of each column (the x-axis), which represent the Winner's digits.  Then, the numbers 0 thru 9 will be randomly drawn down the side of each row (the y-axis), which represent the Loser's digits.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingTwo">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
							Do I need to know anything about basketball?
						</a>
						</h4>
					</div>
					<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
						<div class="panel-body">
							No, you do not need any knowledge of the game of basketball.  Many people believe there is strategy behind picking their squares, but even that is chance.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
							How do I know if I won?
						</a>
						</h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
						<div class="panel-body">
							After a game is over, the winner of the game is determined by finding the column with the LAST digit of the winner's score, and the row with the LAST digit of the loser's score.  The name found in the square is the winner.  For example, let's say I have the square for winner=7 and loser=5, and Purdue beats Indiana 8<b><u>7</u></b> to 7<b><u>5</u></b>.  I would be considered the winner for that game.
							<div class="row">
								<div class="col-md-4 col-sm-4 table-centered">
									<div class="table-responsive" style="margin-top:1em;">
										<table id="faq_grid_winner_example" class="table table-condensed table-bordered">
											<thead>
												<tr>
													<th class="col-lg-1 col-md-1 col-sm-1">&nbsp;</th>
													<th class="col-lg-1 col-md-1 col-sm-1">0</th>
													<th class="col-lg-1 col-md-1 col-sm-1 grid-winner-locator-example">7</th>
													<th class="col-lg-1 col-md-1 col-sm-1">8</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>9</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
												</tr>
												<tr>
													<td class="grid-winner-locator-example">5</td>
													<td>&nbsp;</td>
													<td class="grid-winner-example"><b>Winner</b></td>
													<td>&nbsp;</td>
												</tr>
												<tr>
													<td>2</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingFour">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
							If I have a winning square, will I be notified?
						</a>
						</h4>
					</div>
					<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
						<div class="panel-body">
							If you have provided your email, you will be notified of a winning square.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingFive">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
							I have a winning square... how much did I win?
						</a>
						</h4>
					</div>
					<div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
						<div class="panel-body">
							<div class="row">
								<div class="table-responsive">
									<table id="faq_payouts" class='table table-condensed table-hover'>
										<thead>
											<tr>
												<th>Round</th>
												<th># of<br />Winners</th>
												<th>Payout<br />Per Game</th>
												<th>Total<br />Payout</th>
											</tr>
										</thead>
										<tbody>
											<% if $year >= "2015" %>
												<tr>
													<td>1</td>
													<td>4</td>
													<td>$5</td>
													<td>$20</td>
												</tr>
												<tr>
													<td>2</td>
													<td>32</td>
													<td>$5</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>3</td>
													<td>16</td>
													<td>$10</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>4</td>
													<td>8</td>
													<td>$20</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>5</td>
													<td>4</td>
													<td>$40</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>6</td>
													<td>2</td>
													<td>$80</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>7</td>
													<td>1</td>
													<td>$180</td>
													<td>$180</td>
												</tr>
												<tr class="totalRow">
													<td>Total</td>
													<td>67</td>
													<td>&nbsp;</td>
													<td>$1000</td>
												</tr>
											<% else %>
												<tr>
													<td>2</td>
													<td>32</td>
													<td>$5</td>
													<td>$160</td>
												</tr>
												<tr>
													<td>3</td>
													<td>16</td>
													<td>$8</td>
													<td>$128</td>
												</tr>
												<tr>
													<td>4</td>
													<td>8</td>
													<td>$10</td>
													<td>$80</td>
												</tr>
												<tr>
													<td>5</td>
													<td>4</td>
													<td>$15</td>
													<td>$60</td>
												</tr>
												<tr>
													<td>6</td>
													<td>2</td>
													<td>$20</td>
													<td>$40</td>
												</tr>
												<tr>
													<td>7</td>
													<td>1</td>
													<td>$32</td>
													<td>$32</td>
												</tr>
												<tr class="totalRow">
													<td>Total</td>
													<td>63</td>
													<td>&nbsp;</td>
													<td>$500</td>
												</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingSix">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
							Can I win more than once?
						</a>
						</h4>
					</div>
					<div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
						<div class="panel-body">
							Yes, you can win multiple times.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingSeven">
						<h4 class="panel-title">
						<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
							Are the first four games from Round 1 included?
						</a>
						</h4>
					</div>
					<div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
						<div class="panel-body">
							Yes, beginning in 2015, the first four games will be included.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/grid.html.erb
<% provide(:title, 'Grid') %>
<div class="col-sm-12" align='center'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title" align="center" style="font-size:2em;"><%= $year %> Grid</h3>
    </div>
    <div class="panel-body">
      <% if @winner_digits.blank? or @loser_digits.blank? %>
        <div>Winner/Loser digits have not been added for <%= $year %>.</div>
      <% else %>
        <% winner_digits = @winner_digits.split(',') %>
        <% loser_digits = @loser_digits.split(',') %>
        <div class="panel panel-default">
          <div class="panel-heading">Last Digit of the Winner's Score</div>
          <div class="row">
            <div class="col-sm-12">
              <div class="table-responsive">
                <table id="grid_table" class="table table-condensed table-bordered">
                  <thead>
                    <tr>
                      <th>&nbsp;</th>
                      <% winner_digits.each do |i| %>
                        <th><%= i %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% loser_digits.each do |loser| %>
                      <tr>
                        <td align="center" class='gridLoserDigitsColumn col-sm-1'><%= loser %></td>
                        <% winner_digits.each do |winner| %>
                          <% square = @squares.find_by(winner_digit: winner, loser_digit: loser) %>
                          <% participant_square = @participant_squares.find_by(square_id: square.id) if square.present? %>
                          <% participant = @participants.find(participant_square.participant_id) if participant_square.present? %>
                          <% if square.blank? or participant_square.blank? or participant.blank? %>
                            <td class='col-sm-1'>&nbsp;</td>
                          <% else %>
                            <% square_class = participant.id === @participant_id.to_i ? "highlightParticipantSquares " : "" %>
                            <% if participant.display_name.blank? %>
                              <%= content_tag :td, class: "#{square_class}col-sm-1" do %>
                                <%= participant.first_name %><br /><%= participant.last_name %>
                              <% end %>
                            <% else %>
                              <%= content_tag :td, class: "#{square_class}col-sm-1", title: participant.first_name + ' ' + participant.last_name do %>
                                <%= participant.display_name %>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/results.html.erb
<% provide(:title, 'Results') %>
<% if @payouts.exists? %>
  <% if @participants_with_squares.any? %>
    <% if ($year >= "2015" and @results.count < 67) or ($year <= "2014" and @results.count < 63) %>
      <div class="row">
        <div>
          <% last_updated_at = @year.results_last_updated_at %>
          <% if !last_updated_at.blank? %>
            <%= last_updated_at.strftime('Last updated: %m/%d/%Y at %I:%M %p') %>
          <% end %>
        </div>
        <div>
          <%= link_to 'Refresh', refresh_results_path, id: 'refresh_results_link', remote: true, class: 'btn btn-primary' %>
        </div>
        <br />
      </div>
    <% end %>
    <div class="card-deck-wrapper">
      <div class="card-deck">
        <div class="row">
          <% @participants_with_squares.each do |p_w_sq| %>
            <% resultCounter = 0 %>
            <% totalWon = 0 %>
            <% participant = @participants.find(p_w_sq.id) %>
            <% totalPaid = @participant_squares.where(participant_id: participant.id).count * @year.square_cost %>
            <% participant_results = @results.where(participant_id: participant.id) %>

            <% winning_rounds_text = "&nbsp;".html_safe %>
            
            <% if participant_results.count > 1 %>
              <% winning_rounds_text = "from rounds " %>
            <% elsif participant_results.count == 1 %>
              <% winning_rounds_text = "from round " %>
            <% end %>

            <% participant_results.each do |result| %>
              <% resultCounter += 1 %>
              <% winning_rounds_text.concat("#{result.round}") %>
              <% winning_rounds_text.concat(", ") if resultCounter < participant_results.count %>

              <% @payout = @payouts.find_by(round: result.round).game_payout %>
              <% if !@payout.blank? %>
                <% totalWon += @payout %>
              <% end %>
            <% end %>

            <div class="col-sm-4" style="padding-bottom:1em;">
              <div class="card text-xs-center">
                <div class="card-header">
                  <%= participant.preferred_name %>
                </div>
                <div class="card-block">
                  <p class="card-text">
                    <label>Won</label>
                    <label style="font-weight:normal;">$<%= totalWon %></label>
                    <small class="text-muted"><%= winning_rounds_text %></small>
                  </p>
                  <p class="card-text">
                    <div class="row">
                      <form class="form-inline">
                        <div class="form-group col-sm-6">
                          <label>Paid</label>
                          <label style="font-weight:normal;">$<%= totalPaid %></label>
                        </div>
                        <div class="form-group col-sm-6">
                          <label>Profit</label>
                          
                          <% profit = totalWon - totalPaid %>
                          <% profit_style = "" %>
                          <% if profit > 0 %>
                            <% profit_style = "font-weight:normal;color:green;" %>
                          <% elsif profit < 0 %>
                            <% profit_style = "font-weight:normal;color:red;" %>
                          <% else %>
                            <% profit_style = "font-weight:normal;" %>
                          <% end %>

                          <%= content_tag :label, style: profit_style do %>
                            <span style="color:black;">$</span><%= profit %>
                          <% end %>
                        </div>
                      </form>
                    </div>
                  </p>
                  <p class="card-text">
                    <% square_text = @participant_squares.many? ? "Squares" : "Square" %>
                    <%= link_to image_tag("squares.png"), grid_path(participant_id: participant.id, year: $year), title: "View #{square_text}", "data-toggle" => "tooltip", "data-placement" => "right" %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div style='font-weight:bold;'>Please enter participants for the year.</div>
  <% end %>
<% else %>
  <div style='font-weight:bold;'>Please enter payouts for the year.</div>
<% end %>