config/routes.rb
Rails.application.routes.draw do

  resources :results
  
  root 'pages#results'
  get 'bracket', to: 'pages#bracket'
  get 'grid', to: 'pages#grid'
  get 'faq', to: 'pages#faq'
  get 'refresh_bracket', to: 'pages#refresh_bracket'
  get 'refresh_results', to: 'pages#refresh_results'
  get 'new_bracket', to: 'pages#new_bracket'
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'The Grid Pool', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li id="nav_link_to_results"><%= link_to 'Results', controller: 'pages', action: 'results', year: $year %></li>
        <li id="nav_link_to_bracket"><%= link_to 'Bracket', bracket_path, id: 'bracketLink', remote: true %></li>
        <li id="nav_link_to_grid"><%= link_to 'Grid', grid_path %></li>
        <li id="nav_link_to_faq"><%= link_to 'FAQ', faq_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Select Year<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Year.order(year: :desc).each do |y| %>
              <li><%= link_to y.year, controller: 'pages', action: 'results', year: y.year %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to 'The Grid Pool', root_path, class: 'navbar-brand' %>
  <div class="nav navbar-nav pull-xs-right">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item" id="nav_link_to_results"><%= link_to 'Results', { controller: 'pages', action: 'results', year: $year } %></li>
      <li class="nav-item" id="nav_link_to_bracket"><%= link_to 'Bracket', bracket_path(year: $year), id: 'bracket_link' %></li>
      <li class="nav-item" id="nav_link_to_grid"><%= link_to 'Grid', grid_path(year: $year) %></li>
      <li class="nav-item" id="nav_link_to_faq"><%= link_to 'FAQ', faq_path(year: $year) %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_wait.html.erb
<div id="wait_modal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content" align="center">
      <h2>Loading</h2>
      <p style="padding-bottom:1em;"><%= image_tag("wait.gif", height: '75', width: '75') %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= favicon_link_tag 'favicon.ico' %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	  <meta name="viewport" content="width=device-width,initial-scale=1.0">
	  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	  <link href='http://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Kaushan+Script|Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Istok+Web|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/wait' %>
	</body>
</html>